name: Production Sigstore Prober

on:
  workflow_dispatch:
    inputs:
      triggerPagerDutyTest:
        description: 'Trigger PagerDuty test message'
        required: false
        type: boolean
  schedule:
    # run every 15 minutes, as often as Github Actions allows
    - cron:  '0/15 * * * *'

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  prober:
    uses: ./.github/workflows/reusable-prober.yml
    secrets:
      PAGERDUTY_INTEGRATION_KEY: ${{ secrets.PAGERDUTY_INTEGRATION_KEY }}
    with:
      triggerPagerDutyTest: ${{ github.event.inputs.triggerPagerDutyTest }}
